#!/bin/bash
#
# THIS SCRIPT IS USED TO INSTALL THE PLUGINS OF ZSH
#

git clone --depth=1 https://github.com/romkatv/powerlevel10k.git;
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git;
git clone https://github.com/zsh-users/zsh-autosuggestions.git;
git clone https://github.com/zsh-users/zsh-completions.git;
git clone https://github.com/zsh-users/zsh-history-substring-search.git;
git clone https://github.com/marlonrichert/zsh-autocomplete.git;
